// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASzAqZXqIoGok6srdYgM6ii7i9H2oTjOE',
    appId: '1:762414355642:web:353d9c24828b7c830c1e83',
    messagingSenderId: '762414355642',
    projectId: 'tosbookeventdashboard',
    authDomain: 'tosbookeventdashboard.firebaseapp.com',
    storageBucket: 'tosbookeventdashboard.firebasestorage.app',
    measurementId: 'G-9E2BRZ8TJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuzokMrn6p-_yKsK61HRtT-54RSodrtdw',
    appId: '1:762414355642:android:f5772bd34e292fca0c1e83',
    messagingSenderId: '762414355642',
    projectId: 'tosbookeventdashboard',
    storageBucket: 'tosbookeventdashboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-93-4hb7yoHuDN2dkecpiiXo7jAnRQg8',
    appId: '1:762414355642:ios:1950d8843232640a0c1e83',
    messagingSenderId: '762414355642',
    projectId: 'tosbookeventdashboard',
    storageBucket: 'tosbookeventdashboard.firebasestorage.app',
    iosBundleId: 'com.example.goBusExpress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-93-4hb7yoHuDN2dkecpiiXo7jAnRQg8',
    appId: '1:762414355642:ios:1950d8843232640a0c1e83',
    messagingSenderId: '762414355642',
    projectId: 'tosbookeventdashboard',
    storageBucket: 'tosbookeventdashboard.firebasestorage.app',
    iosBundleId: 'com.example.goBusExpress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASzAqZXqIoGok6srdYgM6ii7i9H2oTjOE',
    appId: '1:762414355642:web:ca648371d56224660c1e83',
    messagingSenderId: '762414355642',
    projectId: 'tosbookeventdashboard',
    authDomain: 'tosbookeventdashboard.firebaseapp.com',
    storageBucket: 'tosbookeventdashboard.firebasestorage.app',
    measurementId: 'G-NXKWHL0YSX',
  );
}
