final Map<String, String> en = {
  'Sign In': 'Sign In',
  'Profile': 'Profile',
  'Home': 'Home',
  'Ticket': 'Ticket',
  'Edit Profile': 'Edit Profile',
  'Languages': 'Languages',
  'Booking History': 'Booking History',
  'Choose Your Language': 'Choose Your Language',
  'Logout': 'Logout',
  'Cancel': 'Cancel',
  'Book Now': 'Book Now',
  'Select Time': 'Select Time',
  'Select Seat': 'Select Seat',
  'Confirm': 'Confirm',
  'Choose Payment': 'Choose Payment',
  'Trip Summary': 'Trip Summary',
  'Direction': 'Direction',
  'Departure Date': 'Departure Date',
  'Seat No': 'Confirm',
  'Unit Price': 'Unit Price',
  'Discount': 'Discount',
  'Net Price': 'Net Price',
  'Note': 'Note',
  'Choose Payment Method': 'Choose Payment Method',
  'Scan to pay with any banking': 'Scan to pay with any banking',
  'Term & Conditions Agreement': 'Term & Conditions Agreement',
  'Booked': 'Booked',
  'Available': 'Available',
  'Yes': 'Yes',
  'No buses available': 'No buses available',
  'Payment was successful': 'Payment was successful',
  'Thanks for riding with us. Have a great trip!':
      'Thanks for riding with us. Have a great trip',
  "Go To HomePage": "Go To HomePage",
  "Search": "Search",
  "Choose Direction": "Choose Direction",
  "New & Promotions": "New & Promotions",
  "Need Help?": "Need Help?",
  "Select Date": "Select Date",
  "Return Date": "Return Date",
  "Please select route, departure and return dates":
      "Please select route, departure and return dates",
  "Cancel Payment?": "Cancel Payment?",
  "Payment Timeout": "Payment Timeout",
  "Your payment session has expired.\nWe will cancel your booking.":
      "Your payment session has expired.\nWe will cancel your booking.",
  "Payment": "Payment",
  "SubTotal: ": "SubTotal: ",
  "Are you sure you want to leave?\nYour booking will be cancelled.":
      "Are you sure you want to leave?\nYour booking will be cancelled.",

  // New Ticket Screen Translations
  'ticket': 'Ticket',
  'upcoming': 'Upcoming',
  'past': 'Past',
  'loading_tickets': 'Loading tickets...',
  'no_upcoming_trips': 'No upcoming trips',
  'upcoming_trips_description': 'Your upcoming trips will appear here.',
  'no_past_trips': 'No past trips',
  'past_trips_description': 'Your completed trips will appear here.',
  'see_details': 'See Details',
  'route_not_available': 'Route information not available',
  'bus_info_not_available': 'Bus Info N/A',
  'seat': 'seat',

  // Ticket Detail Screen Translations
  'ticket_details': 'Ticket Details',
  'loading_ticket_details': 'Loading ticket details...',
  'failed_to_load_ticket': 'Failed to load ticket details',
  'retry': 'Retry',
  'service_type': 'Service Type',
  'travel_date': 'Travel Date',
  'booking_code': 'Booking Code',
  'departure_time': 'Departure Time',
  'arrival_time': 'Arrival Time',
  'distance': 'Distance',
  'duration': 'Duration',
  'total_seats': 'Total Seats',
  'schedule_price': 'Schedule Price',
  'payment_status': 'Payment Status',
  'booking_status': 'Booking Status',
  'departure_location': 'Departure Location',
  'arrival_location': 'Arrival Location',
  'passenger_name': 'Passenger Name',
  'email': 'Email',
  'view_map': 'View Map',
  'ticket_qr_code': 'Ticket QR Code',
  'qr_code': 'QR Code',
  'ticket_id': 'Ticket ID',
  'show_qr_to_driver': 'Show this QR code to the driver',
  'total_amount': 'Total Amount',
  'departure_location_not_available': 'Departure location not available',
  'arrival_location_not_available': 'Arrival location not available',
  'ticket_number': 'Ticket #',
  'booking_number': 'Booking #',
  'issued': 'Issued:',
  "Pay Now": "Pay Now",
  "Would you like to continue or cancel this payment?":
      "Would you like to continue or cancel this payment?",
  "You have an incomplete payment:": "You have an incomplete payment:",
  "Pending Payment": "Pending Payment",
  "Booking ID": "Booking ID:",
  "Amount": "Amount:",
  "No Internet Connection": "No Internet Connection",
  "Please check your internet connection and try again":
      "Please check your internet connection and try again",
  "We are always here to help": "We are always here to help",
  "available_trips": "@count Available Trips",
  "Pay": "Pay \$@amount",
  "logout": "Are you sure you want to logout from your account?",
  "payment_success_title": "🎉 Payment Successful!",
  "payment_success_message":
      "Your booking #@bookingId payment of \$@amount @currency has been confirmed.",
  "select_route": "Select Route",
  "ok": "Ok",
  "qty": "Quantity",
  "edit_profile": "Edit Profile",
  "full_name": "Full Name",
  "phone_number": "Phone Number",
  "save": "Save",
  'arrival': 'Arrival',
  "seats": "Seats",
  "boarding": "Boarding",
  "drop_off": "Drop-off",
  "bus": "Bus",
  "no_seat": "No seat layout available",
  "security": "Security",
  "gobus_wallet_topup_title": "GoBus Wallet Top Up",
  "gobus_wallet_topup_description":
      "Top up now for instant credit! Use your GoBus Wallet balance to pay for your next trip, seat reservations, and more.",
  "payment_selection_title": "Payment Selection",
  "total_payment": "Total Payment",
  "select_payment_method": "Select Payment Method",
  "one_option_available": "1 OPTION AVAILABLE",
  "Bakong": "Bakong",
  "bakong_payment_subtitle": "National Payment System",
  "bakong_info_message":
      "Transactions via Bakong are processed instantly. Please ensure your Bakong app is installed and configured on this device.",
  "confirm_payment": "Confirm Payment",
  "Withdraw": "Withdraw",
  "withdraw_funds": "Withdraw Funds",
  "transfer_details": "TRANSFER DETAILS",
  "available_balance": "Available Balance",
  "select_bank": "Select Bank",
  "choose_your_bank": "Choose your bank",
  "equivalent_to": "EQUIVALENT TO",
  "max_amount": "MAX AMOUNT",
  "account_name": "Account Name",
  "enter_full_name": "Enter full name",
  "account_number": "Account Number",
  "remark_optional": "Remark (Optional)",
  "withdraw_remark_hint": "e.g. Weekly earnings withdrawal",
  "upload_bank_khqr": "Upload Bank KHQR",
  "tap_to_upload_qr": "Tap to upload QR",
  "upload_qr_format": "PNG, JPG or PDF up to 5MB",
  "upload_qr_coming_soon": "Upload feature will be available soon",
  "fill_required_fields": "Please fill in all required fields",
  "withdraw_request_submitted": "Withdraw request submitted successfully",
};
