final Map<String, String> km = {
  'Sign In': 'ចូលគណនី',
  'Profile': 'គណនី',
  'Home': 'ទំព័រដើម',
  'Ticket': 'សំបុត្រ',
  'Edit Profile': 'កែសម្រួលគណនី',
  'Languages': 'ភាសា',
  'Booking History': 'ប្រវត្តិកក់',
  'Choose Your Language': 'ជ្រើសរើសភាសារបស់អ្នក',
  'Logout': 'ចាកចេញ',
  'Cancel': 'បោះបង់',
  'Book Now': 'កក់ឥឡូវនេះ',
  'Select Time': 'ជ្រើសរើសពេលវេលា',
  'Select Seat': 'ជ្រើសរើសកៅអី',
  'Confirm': 'បញ្ជាក់',
  "Choose Payment": "ជ្រើសរើសការទូទាត់",
  "Trip Summary": "សង្ខេបការធ្វើដំណើរ",
  "Direction": "ទិសដៅ",
  "Departure Date": "កាលបរិច្ឆេទចេញដំណើរ",
  "Seat No": "លេខកៅអី",
  "Unit Price": "តម្លៃឯកតា",
  "Discount": "បញ្ចុះតម្លៃ",
  "Net Price": "តម្លៃសរុប",
  "Note": "ចំណាំ",
  "Choose Payment Method": "ជ្រើសរើសវិធីសាស្ត្រទូទាត់",
  "Scan to pay with any banking": "ស្កេនដើម្បីទូទាត់ដោយធនាគារណាមួយ",
  "Term & Conditions Agreement": "ការយល់ព្រមលើលក្ខខណ្ឌ",
  'Booked': 'បានកក់រួចហើយ',
  'Available': 'ទំនេរ',
  'Yes': 'បាទ/ចាស',
  'No buses available': 'មិនមានឡានក្រុងទេ',
  'Payment was successful': 'ការទូទាត់បានជោគជ័យ',
  'Thanks for riding with us. Have a great trip!':
      'អរគុណដែលបានជ្រើសរើសធ្វើដំណើរជាមួយយើង។ សូមឲ្យដំណើររបស់អ្នកប្រកបដោយភាពរីករាយ!',
  "Go To HomePage": "ត្រឡប់ទៅទំព័រដើម",
  "Search": "ស្វែងរក",
  "Choose Direction": "ជ្រើសរើសទិសដៅ",
  "New & Promotions": "ដំណឹង & ប្រម៉ូសិន",
  "Need Help?": "ត្រូវការជំនួយ?",
  "Select Date": "ជ្រើសរើសថ្ងៃ",
  "Return Date": "ថ្ងៃមកវិញ",
  "Please select route, departure and return dates":
      "សូមជ្រើសរើសផ្លូវធ្វើដំណើរ កាលបរិច្ឆេទចេញដំណើរ និងថ្ងៃមកវិញ",
  "Cancel Payment?": "បោះបង់ការទូទាត់",
  "Payment Timeout": "ការទូទាត់បានផុតកំណត់",
  "Your payment session has expired.\nWe will cancel your booking.":
      "រយៈពេលទូទាត់របស់អ្នកបានផុតកំណត់។\nយើងនឹងលុបការកក់របស់អ្នក។",
  "Payment": "ការទូទាត់",
  "SubTotal: ": "សរុប: ",
  "Are you sure you want to leave?\nYour booking will be cancelled.":
      "តើអ្នកប្រាកដថាចង់ចាកចេញមែនទេ?\nការកក់របស់អ្នកនឹងត្រូវបានលុបចោល។",
  
  // New Ticket Screen Translations
  'ticket': 'សំបុត្រ',
  'upcoming': 'នាពេលខាងមុខ',
  'past': 'កន្លងទៅ',
  'loading_tickets': 'កំពុងផ្ទុកសំបុត្រ...',
  'no_upcoming_trips': 'មិនមានដំណើរនាពេលខាងមុខ',
  'upcoming_trips_description': 'ដំណើរនាពេលខាងមុខរបស់អ្នកនឹងបង្ហាញនៅទីនេះ។',
  'no_past_trips': 'មិនមានដំណើរកន្លងទៅ',
  'past_trips_description': 'ដំណើរដែលបានបញ្ចប់របស់អ្នកនឹងបង្ហាញនៅទីនេះ។',
  'see_details': 'មើលព័ត៌មានលម្អិត',
  'route_not_available': 'មិនមានព័ត៌មានផ្លូវ',
  'bus_info_not_available': 'មិនមានព័ត៌មានឡាន',
  'seat': 'កៅអី',
  
  // Ticket Detail Screen Translations
  'ticket_details': 'ព័ត៌មានលម្អិតសំបុត្រ',
  'loading_ticket_details': 'កំពុងផ្ទុកព័ត៌មានសំបុត្រ...',
  'failed_to_load_ticket': 'បរាជ័យក្នុងការផ្ទុកព័ត៌មានសំបុត្រ',
  'retry': 'ព្យាយាមម្តងទៀត',
  'service_type': 'ប្រភេទសេវាកម្ម',
  'travel_date': 'កាលបរិច្ឆេទដំណើរ',
  'booking_code': 'លេខកូដកក់',
  'departure_time': 'ម៉ោងចេញដំណើរ',
  'arrival_time': 'ម៉ោងទៅដល់',
  'distance': 'ចម្ងាយ',
  'duration': 'រយៈពេល',
  'total_seats': 'កៅអីសរុប',
  'schedule_price': 'តម្លៃតាមកាលវិភាគ',
  'payment_status': 'ស្ថានភាពការបង់ប្រាក់',
  'booking_status': 'ស្ថានភាពការកក់',
  'departure_location': 'ទីតាំងចេញដំណើរ',
  'arrival_location': 'ទីតាំងទៅដល់',
  'passenger_name': 'ឈ្មោះអ្នកដំណើរ',
  'email': 'អ៊ីមែល',
  'view_map': 'មើលផែនទី',
  'ticket_qr_code': 'QR កូដសំបុត្រ',
  'qr_code': 'QR កូដ',
  'ticket_id': 'លេខសំបុត្រ',
  'show_qr_to_driver': 'បង្ហាញ QR កូដនេះដល់អ្នកបើកបរ',
  'total_amount': 'ចំនួនទឹកប្រាក់សរុប',
  'departure_location_not_available': 'មិនមានទីតាំងចេញដំណើរ',
  'arrival_location_not_available': 'មិនមានទីតាំងទៅដល់',
  "Pay Now": "បង់ប្រាក់ឥឡូវនេះ",
  "Would you like to continue or cancel this payment?":
      "តើអ្នកចង់បន្ត ឬលុបចោលការទូទាត់នេះ?",
  "You have an incomplete payment:": "អ្នកមានការទូទាត់មិនទាន់បញ្ចប់:",
  "Pending Payment": "កំពុងរង់ចាំការទូទាត់",
  "Booking ID": "លេខកក់សំបុត្រ:",
  "Amount": "Amount",
  "No Internet Connection": "គ្មានការតភ្ជាប់អ៊ីនធឺណិត",
  "Please check your internet connection and try again":
      "សូមពិនិត្យការតភ្ជាប់អ៊ីនធឺណិតរបស់អ្នក ហើយព្យាយាមម្តងទៀត",
  "We are always here to help": "យើងតែងតែស្ថិតនៅទីនេះដើម្បីជួយអ្នក",
  "available_trips": "@count ជើងដំណើរ",
  "Pay": "បង់ប្រាក់ \$@amount",
  "logout":
      "តើអ្នកប្រាកដជាចង់ចេញពីគណនីរបស់អ្នកមែនទេ?",
  "payment_success_title": "🎉 ការទូទាត់បានជោគជ័យ!",
  "payment_success_message": "ការទូទាត់សម្រាប់ការកក់លេខ #@bookingId ចំនួន @amount @currency របស់អ្នក ត្រូវបានបញ្ចប់រួចរាល់។",
  "select_route": "ជ្រើសរើសទិសដៅ",
  "ok": "យល់ព្រម",
};
