final Map<String, String> en = {
  'Sign In': 'Sign In',
  'Profile': 'Profile',
  'Home': 'Home',
  'Ticket': 'Ticket',
  'Edit Profile': 'Edit Profile',
  'Languages': 'Languages',
  'Booking History': 'Booking History',
  'Choose Your Language': 'Choose Your Language',
  'Logout': 'Logout',
  'Cancel': 'Cancel',
  'Book Now': 'Book Now',
  'Select Time': 'Select Time',
  'Select Seat': 'Select Seat',
  'Confirm': 'Confirm',
  'Choose Payment': 'Choose Payment',
  'Trip Summary': 'Trip Summary',
  'Direction': 'Direction',
  'Departure Date': 'Departure Date',
  'Seat No': 'Confirm',
  'Unit Price': 'Unit Price',
  'Discount': 'Discount',
  'Net Price': 'Net Price',
  'Note': 'Note',
  'Choose Payment Method': 'Choose Payment Method',
  'Scan to pay with any banking': 'Scan to pay with any banking',
  'Term & Conditions Agreement': 'Term & Conditions Agreement',
  'Booked': 'Booked',
  'Available': 'Available',
  'Yes': 'Yes',
  'No buses available': 'No buses available',
  'Payment was successful': 'Payment was successful',
  'Thanks for riding with us. Have a great trip!':
      'Thanks for riding with us. Have a great trip',
  "Go To HomePage": "Go To HomePage",
  "Search": "Search",
  "Choose Direction": "Choose Direction",
  "New & Promotions": "New & Promotions",
  "Need Help?": "Need Help?",
  "Select Date": "Select Date",
  "Return Date": "Return Date",
  "Please select route, departure and return dates":
      "Please select route, departure and return dates",
  "Cancel Payment?": "Cancel Payment?",
  "Payment Timeout": "Payment Timeout",
  "Your payment session has expired.\nWe will cancel your booking.":
      "Your payment session has expired.\nWe will cancel your booking.",
  "Payment": "Payment",
  "SubTotal: ": "SubTotal: ",
  "Are you sure you want to leave?\nYour booking will be cancelled.":
      "Are you sure you want to leave?\nYour booking will be cancelled.",
  
  // New Ticket Screen Translations
  'ticket': 'Ticket',
  'upcoming': 'Upcoming',
  'past': 'Past',
  'loading_tickets': 'Loading tickets...',
  'no_upcoming_trips': 'No upcoming trips',
  'upcoming_trips_description': 'Your upcoming trips will appear here.',
  'no_past_trips': 'No past trips',
  'past_trips_description': 'Your completed trips will appear here.',
  'see_details': 'See Details',
  'route_not_available': 'Route information not available',
  'bus_info_not_available': 'Bus Info N/A',
  'seat': 'seat',
  
  // Ticket Detail Screen Translations
  'ticket_details': 'Ticket Details',
  'loading_ticket_details': 'Loading ticket details...',
  'failed_to_load_ticket': 'Failed to load ticket details',
  'retry': 'Retry',
  'service_type': 'Service Type',
  'travel_date': 'Travel Date',
  'booking_code': 'Booking Code',
  'departure_time': 'Departure Time',
  'arrival_time': 'Arrival Time',
  'distance': 'Distance',
  'duration': 'Duration',
  'total_seats': 'Total Seats',
  'schedule_price': 'Schedule Price',
  'payment_status': 'Payment Status',
  'booking_status': 'Booking Status',
  'departure_location': 'Departure Location',
  'arrival_location': 'Arrival Location',
  'passenger_name': 'Passenger Name',
  'email': 'Email',
  'view_map': 'View Map',
  'ticket_qr_code': 'Ticket QR Code',
  'qr_code': 'QR Code',
  'ticket_id': 'Ticket ID',
  'show_qr_to_driver': 'Show this QR code to the driver',
  'total_amount': 'Total Amount',
  'departure_location_not_available': 'Departure location not available',
  'arrival_location_not_available': 'Arrival location not available',
  "Pay Now": "Pay Now",
  "Would you like to continue or cancel this payment?":
      "Would you like to continue or cancel this payment?",
  "You have an incomplete payment:": "You have an incomplete payment:",
  "Pending Payment": "Pending Payment",
  "Booking ID": "Booking ID:",
  "Amount": "Amount:",
  "No Internet Connection": "No Internet Connection",
  "Please check your internet connection and try again":
      "Please check your internet connection and try again",
  "We are always here to help": "We are always here to help",
  "available_trips": "@count Available Trips",
  "Pay": "Pay \$@amount",
  "logout": "Are you sure you want to logout from your account?",
  "payment_success_title": "🎉 Payment Successful!",
  "payment_success_message":
      "Your booking #@bookingId payment of \$@amount @currency has been confirmed.",
  "select_route": "Select Route",
  "ok": "Ok",
  "qty": "Quantity",
};
