final Map<String, String> en = {
  'Sign In': 'Sign In',
  'Profile': 'Profile',
  'Home': 'Home',
  'Ticket': 'Ticket',
  'Edit Profile': 'Edit Profile',
  'Languages': 'Languages',
  'Booking History': 'Booking History',
  'Choose Your Language': 'Choose Your Language',
  'Logout': 'Logout',
  'Cancel': 'Cancel',
  'Book Now': 'Book Now',
  'Select Time': 'Select Time',
  'Select Seat': 'Select Seat',
  'Confirm': 'Confirm',
  'Choose Payment': 'Choose Payment',
  'Trip Summary': 'Trip Summary',
  'Direction': 'Direction',
  'Departure Date': 'Departure Date',
  'Seat No': 'Confirm',
  'Unit Price': 'Unit Price',
  'Discount': 'Discount',
  'Net Price': 'Net Price',
  'Note': 'Note',
  'Choose Payment Method': 'Choose Payment Method',
  'Scan to pay with any banking': 'Scan to pay with any banking',
  'Term & Conditions Agreement': 'Term & Conditions Agreement',
  'Booked': 'Booked',
  'Available': 'Available',
  'Yes': 'Yes',
  'No buses available': 'No buses available',
  'Payment was successful': 'Payment was successful',
  'Thanks for riding with us. Have a great trip!':
      'Thanks for riding with us. Have a great trip',
  "Go To HomePage": "Go To HomePage",
  "Search": "Search",
  "Choose Direction": "Choose Direction",
  "New & Promotions": "New & Promotions",
  "Need Help?": "Need Help?",
  "Select Date": "Select Date",
  "Return Date": "Return Date",
  "Please select route, departure and return dates":
      "Please select route, departure and return dates",
  "Cancel Payment?": "Cancel Payment?",
  "Payment Timeout": "Payment Timeout",
  "Your payment session has expired.\nWe will cancel your booking.":
      "Your payment session has expired.\nWe will cancel your booking.",
  "Payment": "Payment",
  "SubTotal: ": "SubTotal: ",
  "Are you sure you want to leave?\nYour booking will be cancelled.":
      "Are you sure you want to leave?\nYour booking will be cancelled.",
};
