final Map<String, String> km = {
  'Sign In': 'ចូលគណនី',
  'Profile': 'គណនី',
  'Home': 'ទំព័រដើម',
  'Ticket': 'សំបុត្រ',
  'Edit Profile': 'កែសម្រួលគណនី',
  'Languages': 'ភាសា',
  'Booking History': 'ប្រវត្តិកក់',
  'Choose Your Language': 'ជ្រើសរើសភាសារបស់អ្នក',
  'Logout': 'ចាកចេញ',
  'Cancel': 'បោះបង់',
  'Book Now': 'កក់ឥឡូវនេះ',
  'Select Time': 'ជ្រើសរើសពេលវេលា',
  'Select Seat': 'ជ្រើសរើសកៅអី',
  'Confirm': 'បញ្ជាក់',
  "Choose Payment": "ជ្រើសរើសការទូទាត់",
  "Trip Summary": "សង្ខេបការធ្វើដំណើរ",
  "Direction": "ទិសដៅ",
  "Departure Date": "កាលបរិច្ឆេទចេញដំណើរ",
  "Seat No": "លេខកៅអី",
  "Unit Price": "តម្លៃឯកតា",
  "Discount": "បញ្ចុះតម្លៃ",
  "Net Price": "តម្លៃសរុប",
  "Note": "ចំណាំ",
  "Choose Payment Method": "ជ្រើសរើសវិធីសាស្ត្រទូទាត់",
  "Scan to pay with any banking": "ស្កេនដើម្បីទូទាត់ដោយធនាគារណាមួយ",
  "Term & Conditions Agreement": "ការយល់ព្រមលើលក្ខខណ្ឌ",
  'Booked': 'បានកក់រួចហើយ',
  'Available': 'ទំនេរ',
  'Yes': 'បាទ/ចាស',
  'No buses available' : 'មិនមានឡានក្រុងទេ',
};
