final Map<String, String> km = {
  'Sign In': 'ចូលគណនី',
  'Profile': 'គណនី',
  'Home': 'ទំព័រដើម',
  'Ticket': 'សំបុត្រ',
  'Edit Profile': 'កែសម្រួលគណនី',
  'Languages': 'ភាសា',
  'Booking History': 'ប្រវត្តិកក់',
  'Choose Your Language': 'ជ្រើសរើសភាសារបស់អ្នក',
  'Logout': 'ចាកចេញ',
  'Cancel': 'បោះបង់',
  'Book Now': 'កក់ឥឡូវនេះ',
  'Select Time': 'ជ្រើសរើសពេលវេលា',
  'Select Seat': 'ជ្រើសរើសកៅអី',
  'Confirm': 'បញ្ជាក់',
  "Choose Payment": "ជ្រើសរើសការទូទាត់",
  "Trip Summary": "សង្ខេបការធ្វើដំណើរ",
  "Direction": "ទិសដៅ",
  "Departure Date": "កាលបរិច្ឆេទចេញដំណើរ",
  "Seat No": "លេខកៅអី",
  "Unit Price": "តម្លៃឯកតា",
  "Discount": "បញ្ចុះតម្លៃ",
  "Net Price": "តម្លៃសរុប",
  "Note": "ចំណាំ",
  "Choose Payment Method": "ជ្រើសរើសវិធីសាស្ត្រទូទាត់",
  "Scan to pay with any banking": "ស្កេនដើម្បីទូទាត់ជាមួយធនាគារណាមួយ",
  "Term & Conditions Agreement": "ការយល់ព្រមលើលក្ខខណ្ឌ",
  'Booked': 'បានកក់រួចហើយ',
  'Available': 'ទំនេរ',
  'Yes': 'បាទ/ចាស',
  'No buses available': 'មិនមានឡានក្រុងទេ',
  'Payment was successful': 'ការទូទាត់បានជោគជ័យ',
  'Thanks for riding with us. Have a great trip!':
      'អរគុណដែលបានជ្រើសរើសធ្វើដំណើរជាមួយយើង។ សូមឲ្យដំណើររបស់អ្នកប្រកបដោយភាពរីករាយ!',
  "Go To HomePage": "ត្រឡប់ទៅទំព័រដើម",
  "Search": "ស្វែងរក",
  "Choose Direction": "ជ្រើសរើសទិសដៅ",
  "New & Promotions": "ដំណឹង & ប្រម៉ូសិន",
  "Need Help?": "ត្រូវការជំនួយ?",
  "Select Date": "ជ្រើសរើសថ្ងៃ",
  "Return Date": "ថ្ងៃមកវិញ",
  "Please select route, departure and return dates":
      "សូមជ្រើសរើសផ្លូវធ្វើដំណើរ កាលបរិច្ឆេទចេញដំណើរ និងថ្ងៃមកវិញ",
  "Cancel Payment?": "បោះបង់ការទូទាត់",
  "Payment Timeout": "ការទូទាត់បានផុតកំណត់",
  "Your payment session has expired.\nWe will cancel your booking.":
      "រយៈពេលទូទាត់របស់អ្នកបានផុតកំណត់។\nយើងនឹងលុបការកក់របស់អ្នក។",
  "Payment": "ការទូទាត់",
  "SubTotal: ": "សរុប: ",
  "Are you sure you want to leave?\nYour booking will be cancelled.":
      "តើអ្នកប្រាកដថាចង់ចាកចេញមែនទេ?\nការកក់របស់អ្នកនឹងត្រូវបានលុបចោល។",

  // New Ticket Screen Translations
  'ticket': 'សំបុត្រ',
  'upcoming': 'នាពេលខាងមុខ',
  'past': 'កន្លងទៅ',
  'loading_tickets': 'កំពុងផ្ទុកសំបុត្រ...',
  'no_upcoming_trips': 'មិនមានដំណើរនាពេលខាងមុខ',
  'upcoming_trips_description': 'ដំណើរនាពេលខាងមុខរបស់អ្នកនឹងបង្ហាញនៅទីនេះ។',
  'no_past_trips': 'មិនមានដំណើរកន្លងទៅ',
  'past_trips_description': 'ដំណើរដែលបានបញ្ចប់របស់អ្នកនឹងបង្ហាញនៅទីនេះ។',
  'see_details': 'មើលព័ត៌មានលម្អិត',
  'route_not_available': 'មិនមានព័ត៌មានផ្លូវ',
  'bus_info_not_available': 'មិនមានព័ត៌មានឡាន',
  'seat': 'កៅអី',

  // Ticket Detail Screen Translations
  'ticket_details': 'ព័ត៌មានលម្អិតសំបុត្រ',
  'loading_ticket_details': 'កំពុងផ្ទុកព័ត៌មានសំបុត្រ...',
  'failed_to_load_ticket': 'បរាជ័យក្នុងការផ្ទុកព័ត៌មានសំបុត្រ',
  'retry': 'ព្យាយាមម្តងទៀត',
  'service_type': 'ប្រភេទសេវាកម្ម',
  'travel_date': 'កាលបរិច្ឆេទដំណើរ',
  'booking_code': 'លេខកូដកក់',
  'departure_time': 'ម៉ោងចេញដំណើរ',
  'arrival_time': 'ម៉ោងទៅដល់',
  'distance': 'ចម្ងាយ',
  'duration': 'រយៈពេល',
  'total_seats': 'កៅអីសរុប',
  'schedule_price': 'តម្លៃតាមកាលវិភាគ',
  'payment_status': 'ស្ថានភាពការបង់ប្រាក់',
  'booking_status': 'ស្ថានភាពការកក់',
  'departure_location': 'ទីតាំងចេញដំណើរ',
  'arrival_location': 'ទីតាំងទៅដល់',
  'passenger_name': 'ឈ្មោះអ្នកដំណើរ',
  'email': 'អ៊ីមែល',
  'view_map': 'មើលផែនទី',
  'ticket_qr_code': 'QR កូដសំបុត្រ',
  'qr_code': 'QR កូដ',
  'ticket_id': 'លេខសំបុត្រ',
  'show_qr_to_driver': 'បង្ហាញ QR កូដនេះដល់អ្នកបើកបរ',
  'total_amount': 'ចំនួនទឹកប្រាក់សរុប',
  'departure_location_not_available': 'មិនមានទីតាំងចេញដំណើរ',
  'arrival_location_not_available': 'មិនមានទីតាំងទៅដល់',
  'ticket_number': 'សំបុត្រលេខ #',
  'booking_number': 'លេខកក់ #',
  'issued': 'ចេញផ្សាយ:',
  "Pay Now": "បង់ប្រាក់ឥឡូវនេះ",
  "Would you like to continue or cancel this payment?":
      "តើអ្នកចង់បន្ត ឬលុបចោលការទូទាត់នេះ?",
  "You have an incomplete payment:": "អ្នកមានការទូទាត់មិនទាន់បញ្ចប់:",
  "Pending Payment": "កំពុងរង់ចាំការទូទាត់",
  "Booking ID": "លេខកក់សំបុត្រ:",
  "Amount": "Amount",
  "No Internet Connection": "គ្មានការតភ្ជាប់អ៊ីនធឺណិត",
  "Please check your internet connection and try again":
      "សូមពិនិត្យការតភ្ជាប់អ៊ីនធឺណិតរបស់អ្នក ហើយព្យាយាមម្តងទៀត",
  "We are always here to help": "យើងតែងតែស្ថិតនៅទីនេះដើម្បីជួយអ្នក",
  "available_trips": "@count ជើងដំណើរ",
  "Pay": "បង់ប្រាក់ \$@amount",
  "logout": "តើអ្នកប្រាកដជាចង់ចេញពីគណនីរបស់អ្នកមែនទេ?",
  "payment_success_title": "🎉 ការទូទាត់បានជោគជ័យ!",
  "payment_success_message":
      "ការទូទាត់សម្រាប់ការកក់លេខ #@bookingId ចំនួន @amount @currency របស់អ្នក ត្រូវបានបញ្ចប់រួចរាល់។",
  "select_route": "ជ្រើសរើសទិសដៅ",
  "ok": "យល់ព្រម",
  "qty": "បរិមាណ",
  "edit_profile": "កែប្រូហ្វាយល៍",
  "full_name": "ឈ្មោះពេញ",
  "phone_number": "លេខទូរស័ព្ទ",
  "save": "រក្សាទុក",
  'arrival': 'ម៉ោងទៅដល់',
  "seats": "កៅអី",
  "boarding": "ទីតាំងឡើង",
  "drop_off": "ទីតាំងចុះ",
  "bus": "រថយន្ត",
  "no_seat": "មិនមានកៅអីនោះទេ",
  "security": "សុវត្ថិភាព",
  "gobus_wallet_topup_title": "បញ្ចូលប្រាក់ GoBus Wallet",
  "gobus_wallet_topup_description":
      "បញ្ចូលប្រាក់ឥឡូវនេះ ដើម្បីទទួលបានឥណទានភ្លាមៗ! អ្នកអាចប្រើសមតុល្យ GoBus Wallet សម្រាប់បង់ថ្លៃដំណើរបន្ទាប់ ការកក់កៅអី និងសេវាកម្មផ្សេងៗទៀត។",
  "payment_selection_title": "ជ្រើសរើសការទូទាត់",
  "total_payment": "ចំនួនទូទាត់សរុប",
  "select_payment_method": "ជ្រើសរើសវិធីសាស្ត្រទូទាត់",
  "one_option_available": "មានជម្រើស ១",
  "Bakong": "បាគង",
  "bakong_payment_subtitle": "ប្រព័ន្ធទូទាត់ជាតិ",
  "bakong_info_message":
      "ប្រតិបត្តិការតាមរយៈ Bakong ត្រូវបានដំណើរការភ្លាមៗ។ សូមប្រាកដថាកម្មវិធី Bakong របស់អ្នកបានដំឡើង និងកំណត់រចនាសម្ព័ន្ធលើឧបករណ៍នេះរួចរាល់។",
  "confirm_payment": "បញ្ជាក់ការទូទាត់",
  "Withdraw": "ដកប្រាក់",
  "withdraw_funds": "ដកប្រាក់",
  "transfer_details": "ព័ត៌មានផ្ទេរប្រាក់",
  "available_balance": "សមតុល្យដែលមាន",
  "select_bank": "ជ្រើសរើសធនាគារ",
  "choose_your_bank": "ជ្រើសរើសធនាគាររបស់អ្នក",
  "equivalent_to": "ស្មើនឹង",
  "max_amount": "ចំនួនអតិបរមា",
  "account_name": "ឈ្មោះគណនី",
  "enter_full_name": "បញ្ចូលឈ្មោះពេញ",
  "account_number": "លេខគណនី",
  "remark_optional": "កំណត់សម្គាល់ (ជាជម្រើស)",
  "withdraw_remark_hint": "ឧ. ដកប្រាក់ចំណូលប្រចាំសប្តាហ៍",
  "upload_bank_khqr": "ផ្ទុកឡើង Bank KHQR",
  "tap_to_upload_qr": "ចុចដើម្បីផ្ទុកឡើង QR",
  "upload_qr_format": "PNG, JPG ឬ PDF ទំហំអតិបរមា 5MB",
  "upload_qr_coming_soon": "មុខងារផ្ទុកឡើងនឹងមានឆាប់ៗ",
  "fill_required_fields": "សូមបំពេញព័ត៌មានចាំបាច់ទាំងអស់",
  "withdraw_request_submitted": "សំណើដកប្រាក់ត្រូវបានផ្ញើដោយជោគជ័យ",
  "payment_details": "ព័ត៌មានការទូទាត់",
  "base_fare": "តម្លៃសំបុត្រដើម",
  "discount": "បញ្ចុះតម្លៃ",
  "total_paid": "សរុបទឹកប្រាក់បានបង់",
  "passenger": "អ្នកដំណើរ",
  "wallet": "កាបូប",
  "customer_support": "ផ្នែកជំនួយអតិថិជន",
  "special_offer": "ការផ្តល់ជូនពិសេស",
  "pay_instantly_with_your_balance": "ទូទាត់ភ្លាមៗដោយប្រើសមតុល្យរបស់អ្នក",
  "insufficient_balance": "សមតុល្យមិនគ្រប់គ្រាន់ (មានត្រឹម \$%s)",
  "top_up": "បញ្ចូលលុយ",
  "available_balance_custom": "សមតុល្យដែលមាន៖ \$@balance",
  "insufficient_balance_custom": "មិនគ្រប់គ្រាន់ (\$@balance ដែលមាន)",
  "wallet_pin": "លេខសម្ងាត់កាបូប",
  "enter_pin_to_pay": "បញ្ចូលលេខសម្ងាត់ដើម្បីបញ្ចប់ការទូទាត់",
  "session_expired_enter_pin": "សម័យប្រើប្រាស់បានផុតកំណត់។ បញ្ចូលលេខសម្ងាត់ដើម្បីបន្ត។",
  "wallet_pin_required_hint": "ត្រូវការ PIN — អ្នកនឹងត្រូវបញ្ចូលនៅពេលចុច Pay",
  "wallet_description_label": "បរិយាយ",
  "wallet_description_hint": "ឧ. ការទូទាត់សំបុត្រឡានក្រុង",
  
  // Booking Status Translations
  "status_confirmed": "បានបញ្ជាក់",
  "status_pending": "កំពុងរង់ចាំ",
  "status_cancelled": "បានលុបចោល",
  "status_failed": "បរាជ័យ",
  "status_refund_requested": "បានស្នើសុំសងប្រាក់វិញ",
  "status_refunded": "បានសងប្រាក់វិញ",
  
  // Payment Status Translations
  "status_paid": "បានបង់ប្រាក់",
  "status_unpaid": "មិនទាន់បង់ប្រាក់",
  "status_success": "ជោគជ័យ",
  "status_completed": "បានបញ្ចប់",
  "status_processing": "កំពុងដំណើរការ",
  
  "booking": "ការកក់",
  "payment": "ការទូទាត់",
  
  // Refund Screen Translations
  "my_refunds": "ការសងប្រាក់វិញរបស់ខ្ញុំ",
  "all": "ទាំងអស់",
  "approved": "បានអនុម័ត",
  "rejected": "បានបដិសេធ",
  "no_refunds_found": "រកមិនឃើញការសងប្រាក់វិញ",
  "refunds_appear_here": "សំណើសងប្រាក់វិញរបស់អ្នកនឹងបង្ហាញនៅទីនេះ",
  "failed_to_load_refunds": "បរាជ័យក្នុងការផ្ទុកការសងប្រាក់វិញ",
  "refund_details": "ព័ត៌មានលម្អិតការសងប្រាក់វិញ",
  "refund": "សងប្រាក់វិញ",
  "requested": "បានស្នើសុំ",
  "refund_amount": "ចំនួនទឹកប្រាក់សងវិញ",
  "amount": "ចំនួនទឹកប្រាក់",
  "processed_on": "ដំណើរការនៅ",
  "reason": "មូលហេតុ",
  "trip_details": "ព័ត៌មានដំណើរ",
  "booking_info": "ព័ត៌មានការកក់",
  "booking_id": "លេខកក់",
  "booked_on": "កក់នៅ",
  "admin_note": "កំណត់ចំណាំរដ្ឋបាល",
  "go_back": "ត្រឡប់ក្រោយ",
  "loading_refund_details": "កំពុងផ្ទុកព័ត៌មានការសងប្រាក់វិញ...",
  "failed_to_load_refund_details": "បរាជ័យក្នុងការផ្ទុកព័ត៌មានការសងប្រាក់វិញ",
  
  // Refund Status Translations
  "status_approved": "បានអនុម័ត",
  "status_rejected": "បានបដិសេធ",

  // Refund Request Dialog
  "request_refund": "ស្នើសុំសងប្រាក់វិញ",
  "confirm_refund_title": "បញ្ជាក់ការស្នើសុំសងប្រាក់វិញ",
  "confirm_refund_message": "តើអ្នកប្រាកដថាចង់ស្នើសុំសងប្រាក់ \$@amount សម្រាប់ការកក់នេះ?",
  "refund_success": "ការស្នើសុំសងប្រាក់វិញត្រូវបានដាក់ជូនដោយជោគជ័យ",
  "refund_failed": "បរាជ័យក្នុងការដាក់ជូនការស្នើសុំសងប្រាក់វិញ",
  "refund_requested": "បានស្នើសុំសងប្រាក់វិញ",
  "processing_refund": "កំពុងដំណើរការការសងប្រាក់",
  "please_wait": "សូមរង់ចាំ...",
  "cancel": "បោះបង់",
  "confirm": "បញ្ជាក់",

  // Cancel Top-Up Dialog
  "cancel_topup_title": "បោះបង់ការបញ្ចូលប្រាក់?",
  "cancel_topup_message":
      "ការទូទាត់របស់អ្នកនៅកំពុងដំណើរការ។\nបើអ្នកត្រឡប់ក្រោយឥឡូវ ការបញ្ចូលប្រាក់អាចនឹងមិនបញ្ចប់ទេ។",
  "keep_waiting": "រង់ចាំបន្ត",
  "cancel_topup": "បោះបង់ការបញ្ចូលប្រាក់",

  // Top-Up Wallet Screen
  "top_up_wallet": "បញ្ចូលប្រាក់ក្នុងកាបូប",
  "enter_amount": "បញ្ចូលចំនួន",
  "total_balance": "សមតុល្យសរុប",
  "please_enter_valid_amount": "សូមបញ្ចូលចំនួនទឹកប្រាក់ត្រឹមត្រូវ",

  // Top-Up Success Screen
  "topup_success_title": "🎉 បញ្ចូលប្រាក់បានជោគជ័យ!",
  "topup_success_message":
      "ប្រាក់ត្រូវបានបញ្ចូលចូលកាបូបរបស់អ្នកដោយជោគជ័យ។\nសមតុល្យរបស់អ្នករួចរាល់សម្រាប់ប្រើ។",

  // Payment error/retry dialog
  "try_again": "ព្យាយាមម្តងទៀត",
  "payment_not_completed": "ការទូទាត់មិនបានបញ្ចប់",
  "payment_failed_message":
      "ការទូទាត់របស់អ្នកមិនអាចបញ្ចប់បានទេ។ សូមព្យាយាមម្តងទៀត ឬបោះបង់ការកក់។",
  "payment_pending": "ការទូទាត់កំពុងដំណើរការ",
  "payment_pending_message":
      "ការទូទាត់របស់អ្នកកំពុងដំណើរការ។ អ្នកអាចព្យាយាមម្តងទៀត ឬបោះបង់ការកក់។",
  "payment_error_message":
      "យើងមិនអាចផ្ទៀងផ្ទាត់ស្ថានភាពការទូទាត់របស់អ្នកបានទេ។ សូមព្យាយាមម្តងទៀត ឬបោះបង់ការកក់។",
  "cancel_booking": "បោះបង់ការកក់",

  // Wallet Transaction List
  "All transactions loaded": "ប្រតិបត្តិការទាំងអស់ត្រូវបានផ្ទុក",

  // Wallet Screen
  'My Wallet': 'កាបូបរបស់ខ្ញុំ',
  'Available Balance': 'សមតុល្យដែលមាន',
  'Top Up': 'បញ្ចូលលុយ',
  'Recent Transactions': 'ប្រតិបត្តិការថ្មីៗ',
  'No Transactions Yet': 'មិនទាន់មានប្រតិបត្តិការទេ',
  'Your transaction history will appear here':
      'ប្រវត្តិប្រតិបត្តិការរបស់អ្នកនឹងបង្ហាញនៅទីនេះ',
  'Failed to load transactions': 'បរាជ័យក្នុងការផ្ទុកប្រតិបត្តិការ',
  'Retry': 'ព្យាយាមម្តងទៀត',

  // Transaction Type Labels
  'Payment': 'ការទូទាត់',
  'Refund': 'សងប្រាក់វិញ',
  'Withdrawal': 'ដកប្រាក់',
  'Bonus': 'ប្រាក់រង្វាន់',
  'Transaction': 'ប្រតិបត្តិការ',

  // Transaction Status Labels
  'Completed': 'បានបញ្ចប់',
  'Pending': 'កំពុងរង់ចាំ',
  'Failed': 'បរាជ័យ',
  'Cancelled': 'បានលុបចោល',
};
